spring.application.name=Fintrack
server.port=8081

#spring.datasource.url=${DATASOURCE_URL}
#spring.datasource.username=${DATASOURCE_USER}
#spring.datasource.password=${DATASOURCE_PASSWORD}
#frontend.url=${FRONTEND_URL}

spring.datasource.url=jdbc:postgresql://localhost:5432/fintrack
spring.datasource.username=postgres
spring.datasource.password=Shiva@2906
frontend.url=http://localhost:5173
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

security.jwt.secret=3cfa76ef15467c1c0ea519f8fr057a80fcd04a7420f8e8bcd0a1237c272e007b
security.jwt.expiration-ms=900000
security.jwtRefreshExpirationMs=604800000

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=10m

spring.jpa.show-sql=true
