package com.financeTracking.Fintrack.TransactionService.Model;

public enum PaymentType {

    CASH_PHYSICAL_CURRENCY,
    DEBIT_CARD,
    CREDIT_CARD,
    PREPAID_CARDS,
    UPI_GOOGLEPAY,
    UPI_PHONEPE,
    UPI_BHIM,
    UPI_PAYTM,
    UPI_AMAZON_PAY,
    DIGITAL_WALLET_PAYTM,
    DIGITAL_WALLET_MOBIKWIK,
    DIGITAL_WALLET_AMAZON_PAY,
    DIGITAL_WALLET_PHONEPE,
    BANK_TRANSFERS_NEFT,
    BANK_TRANSFERS_RTGS,
    BANK_TRANSFERS_IMPS,
    NET_BANKING,
    BNPL_LAZYPAY,
    BNPL_ZESTMONEY,
    AUTOPAY_RECURRING_PAYMENTS,
    CHEQUES,
    DEMAND_DRAFTS,
    OTHERS
}
